version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./wallets:/app/wallets
    
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: